name: iplan # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: iplan
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  iplan:
    after: [rustup]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/iman-salmani/iplan.git
    source-tag: 'v1.6.0'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/iplan/current/usr
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/iplan.patch
      sed -i 's|Icon=ir.imansalmani.IPlan|Icon=snap.iplan.ir.imansalmani.IPlan|' data/ir.imansalmani.IPlan.desktop.in
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/iplan/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      find $CRAFT_PART_INSTALL/meta/gui/icons -type f -not -name 'ir.imansalmani.IPlan*' -exec rm {} + -o -type d -empty -exec rmdir {} +
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [usr/share/metainfo/ir.imansalmani.IPlan.metainfo.xml]
    organize:
      snap/iplan/current: .

slots:
  iplan:
    interface: dbus
    bus: session
    name: ir.imansalmani.IPlan
apps:
  iplan:
    command: usr/bin/iplan
    extensions: [gnome]
    common-id: ir.imansalmani.IPlan
